SIT:
  EMPLOYEE: 'SCOTT/TIGER@127.0.0.1:1522/MRTROUBLE'
  SALARY: 'SCOTT/TIGER@127.0.0.1:1522/MRTROUBLE'
UAT:
  EMPLOYEE: 'SCOTT/TIGER@127.0.0.1:1522/MRTROUBLE'
  SALARY: 'SCOTT/TIGER@127.0.0.1:1522/MRTROUBLE'
